### PR TITLE
fix #85:  TSV bundle - is not populating column "diagnostic pcr Ct"

### LINKED ISSUE #85: TSV bundle - is not populating column "diagnostic pcr Ct"
Steps to reproduce the issue:

1. Go to portal
2. Select 1 or more analysis with a Diagnostic Pcr CT value.
3. Download "Metadata & fasta files"
4. the column "diagnostic pcr Ct" is empty

**Expected:**
The column "diagnostic pcr Ct" must contain data.

### PR DESCRIPTION
**Pull request by leoraba**
Fix issue #85

### CODE REVIEW

File: src/main/java/org/cancogenvirusseq/singularity/components/utils/TsvUtils.java [hunk 1]
```diff
@@ -179,14 +179,14 @@ private static String analysisDocumentToTsvRow(AnalysisDocument analysisDocument
 
   private static String[] jsonNodeToString(JsonNode... jsonNodeList) {
     return Arrays.stream(jsonNodeList).map(jsonNode -> {
-      if (jsonNode == null) {
+      if (jsonNode == null || jsonNode.isNull()) {
```
Comment (caravinci) [inline src/main/java/org/cancogenvirusseq/singularity/components/utils/TsvUtils.java:182]: What's the difference here?
wouldn't `if (jsonNode.isNull())` suffice?

Comment (leoraba) [reply src/main/java/org/cancogenvirusseq/singularity/components/utils/TsvUtils.java:182]: the first condition `jsonNode == null` checks if the object itself is not present and avoids a NullPointerException; the second condition `jsonNode.isNull()` checks if the value is explicitly set to null

Comment (caravinci) [reply src/main/java/org/cancogenvirusseq/singularity/components/utils/TsvUtils.java:182]: Thanks for clarifying that for me 🙏

**Review by caravinci — APPROVED** [review]
